$TR,"Adam"$
$ID,2$$TR,"TempleOS"$
$ID,2$$TR,"SysMsgFlags"$
$ID,2$sys_msg_flags[0]=0x205;
$ID,-2$$TR,"SysRegVer"$
$ID,2$registry_version=1.010;
$ID,-2$$ID,-2$$ID,-2$$TR,"DemoCompany"$
$ID,2$$TR,"Game1"$
$ID,2$F64 best_score=1.23;
$TR,"SimpleVal"$
$ID,2$1234;
$ID,-2$$ID,-2$$ID,-2$$TR,"TempleOS"$
$ID,2$$TR,"ZoneOut"$
$ID,2$F64 best_score=9999.0000;
$ID,-2$$TR,"BirdLand"$
$ID,2$F64 best_score=9999.0000;
$ID,-2$$TR,"RawHide"$
$ID,2$F64 best_score=9999.0000;
$ID,-2$$TR,"KeepAway"$
$ID,2$I64 best_score0=0,best_score1=9999;
$ID,-2$$TR,"Wenceslas"$
$ID,2$F64 best_score=9999.0000;
$ID,-2$$TR,"Bomber"$
$ID,2$I64 best_score=99999;
$ID,-2$$TR,"Timeout"$
$ID,2$I64 best_score=14797;
$ID,-2$$TR,"FPS"$
$ID,2$F64 best_score=57.8336;
$ID,-2$$TR,"EagleDive"$
$ID,2$I64 best_score=1;
$ID,-2$$TR,"XCaliber"$
$ID,2$I64 best_score=118;
$ID,-2$$ID,-2$